### ISSUE TITLE
Parent column styling overrides child columns

### ISSUE THREAD

**Issue by brian-griffin** [andrewjtait/conflexgrids#1]
With the following mark-up, the child `content-left` and `content-right` areas will have widths of `33.3333%` due to the parent `columns-3` overriding the `columns-2` style expected (higher column number values override lower values due to the order they're generated).

``` html
<div class="column-set columns-3">
  <div class="column-container">
    <!-- some side menu -->
  </div>
  <div class="column-container span-2">
    <h2>My heading</h2>
    <div class="column-set columns-2">
      <div class="column-container"><!-- content_left --></div>
      <div class="column-container"><!-- content_right --></div>
    </div>
  </div>
</div>
```

I've fixed this locally by changing

``` sass
    &.columns-#{$i} {
      .column-container {
        width: $width;
      }
      ...
```

to

``` sass
    &.columns-#{$i} {
      > .column-container {
        width: $width;
      }
      ...
```

in this section:
https://github.com/andrewjtait/conflexgrids/blob/master/sass/conflexgrids.scss#L19-L22

**Comment by andrewjtait** [comment]
I accept PR's :wink:
